name: Publish Docker image
on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths:
#      - "**/*.go"
#      - "go.mod"
#      - "go.sum"
#      - ".github/workflows/*.yml"
#    tags:
#      - 'v*'
#  pull_request:
#    branches:
#      - 'master'
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: server/scripts/Dockerfile
          platforms: linux/arm,linux/arm64,linux/amd64
          push: true
          tags: |
            hhhflow/xrayr:1.0.0
            hhhflow/xrayr:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max